<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H3R6GON" name="com.regression.TestCases.TC_189_AdministerS8_byAIN_InvalidPin" tests="1" failures="0" timestamp="4 Aug 2017 12:24:50 GMT" time="26.981" errors="1">
  <testcase name="administerS8_byAIN_InvalidPin" time="26.981" classname="com.regression.TestCases.TC_189_AdministerS8_byAIN_InvalidPin">
    <error type="java.lang.UnsatisfiedLinkError" message="org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V">
      <![CDATA[java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.Mem.gather(Native Method)
	at org.hyperic.sigar.Mem.fetch(Mem.java:30)
	at org.hyperic.sigar.Sigar.getMem(Sigar.java:304)
	at testpoint.StreamTest.Stop_SiteMon_Synthetic(StreamTest.java:247)
	at com.regression.TestCases.TC_189_AdministerS8_byAIN_InvalidPin.administerS8_byAIN_InvalidPin(TC_189_AdministerS8_byAIN_InvalidPin.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- administerS8_byAIN_InvalidPin -->
</testsuite> <!-- com.regression.TestCases.TC_189_AdministerS8_byAIN_InvalidPin -->
